/**
 * Emits `dist/world.css`.
 *
 * The three-state theme rule is implemented here once, generated rather than
 * hand-written, because hand-writing it is where the classic unreadable-page bug comes
 * from. A viewer is in one of three states, not two:
 *
 *   - explicit light  -> `data-theme="light"` on the root
 *   - explicit dark   -> `data-theme="dark"`
 *   - system (default)-> nothing stamped at all, and only `prefers-color-scheme` decides
 *
 * So the bare `:root` block carries the complete light palette; the media query
 * redefines only the tokens and is guarded so an explicit light choice still beats a
 * dark OS; and the `[data-theme="dark"]` block redefines them again so the toggle wins
 * in the other direction.
 */
import { COLORS } from "./color.ts";
import {
  DURATION,
  EASING,
  ELEVATION,
  FONTS,
  LAYOUT,
  LINE_HEIGHT,
  RADIUS,
  SPACE,
  TRACKING,
  TYPE_SIZE,
  WEIGHT,
} from "./scale.ts";

const PREFIX = "--w";

function block(lines: string[], indent = "  "): string {
  return lines.map((l) => indent + l).join("\n");
}

/** Everything made of colour, and therefore everything that must be themed. */
function themedVars(theme: "light" | "dark"): string[] {
  return [
    ...COLORS.map((c) => `${PREFIX}-color-${c.name}: ${c[theme]};`),
    ...Object.entries(ELEVATION).map(([k, v]) => `${PREFIX}-elevation-${k}: ${v[theme]};`),
  ];
}

export function emitCss(): string {
  const families = FONTS.filter((f) => f.webfont)
    // Google Fonts requires "+" for spaces in a family name; a raw space silently
    // fails the request and the whole page falls back.
    .map((f) => `family=${f.webfont!.family.replace(/ /g, "+")}:${f.webfont!.axes}`)
    .join("&");

  const scale: string[] = [
    ...FONTS.map((f) => `${PREFIX}-font-${f.name}: ${f.stack};`),
    ...Object.entries(TYPE_SIZE).map(([k, v]) => `${PREFIX}-size-${k}: ${v / 16}rem;`),
    ...Object.entries(LINE_HEIGHT).map(([k, v]) => `${PREFIX}-leading-${k}: ${v};`),
    ...Object.entries(TRACKING).map(([k, v]) => `${PREFIX}-tracking-${k}: ${v};`),
    ...Object.entries(WEIGHT).map(([k, v]) => `${PREFIX}-weight-${k}: ${v};`),
    ...Object.entries(SPACE).map(([k, v]) => `${PREFIX}-space-${k}: ${v}px;`),
    ...Object.entries(RADIUS).map(([k, v]) => `${PREFIX}-radius-${k}: ${v}px;`),
    ...Object.entries(DURATION).map(([k, v]) => `${PREFIX}-duration-${k}: ${v}ms;`),
    ...Object.entries(EASING).map(([k, v]) => `${PREFIX}-easing-${k}: ${v};`),
    ...Object.entries(LAYOUT).map(
      ([k, v]) => `${PREFIX}-layout-${k}: ${typeof v === "number" ? `${v}px` : v};`
    ),
  ];

  return `/* Generated by packages/world. Do not edit by hand - edit src/ and run \`npm run build\`. */
@import url("https://fonts.googleapis.com/css2?${families}&display=swap");

:root {
  color-scheme: light dark;

${block(themedVars("light"))}

${block(scale)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${block(themedVars("dark"), "    ")}
  }
}

:root[data-theme="dark"] {
${block(themedVars("dark"))}
}

@media (prefers-reduced-motion: reduce) {
  :root {
${block(
  Object.keys(DURATION).map((k) => `${PREFIX}-duration-${k}: 1ms;`),
  "    "
)}
  }
}

/* The ground must be painted explicitly. A transparent body borrows whatever ground
   the host is painting, which is how a page ends up showing one theme's text on the
   other theme's background. */
html {
  background: var(${PREFIX}-color-ground);
}

body {
  margin: 0;
  background: var(${PREFIX}-color-ground);
  color: var(${PREFIX}-color-ink);
  font-family: var(${PREFIX}-font-body);
  font-size: var(${PREFIX}-size-body);
  line-height: var(${PREFIX}-leading-read);
  -webkit-font-smoothing: antialiased;
}

:where(a) {
  color: var(${PREFIX}-color-indigo);
}

:where(:focus-visible) {
  outline: 2px solid var(${PREFIX}-color-indigo);
  outline-offset: 2px;
  border-radius: var(${PREFIX}-radius-edge);
}
`;
}
