/**
 * `dist/scenes.css` - the film's layer over `world.css`.
 *
 * Everything here resolves to a token. There is no colour, no font stack, no type size and
 * no spacing value written out in this file, and `check-scenes` fails the build over a
 * single hex literal. That is not tidiness: the moment one scene carries its own colour,
 * the film and the app have started to drift and nobody will notice until a family watches
 * something that looks almost, but not quite, like the app they saved it in.
 *
 * Exactly three raw numbers are allowed through, and the check knows all three:
 * `FRAME.width`, `FRAME.height` and `FILM_ROOT_PX`.
 *
 * `FILM_ROOT_PX` is the one genuinely new decision. The type scale is in `rem`, so setting
 * the film's root size scales every size token together and keeps the ratios between them
 * exactly as they are in the app. Spacing tokens are in `px` and deliberately do not scale:
 * 128px of breath is 128px of breath, and a 1920-wide frame watched from a sofa wants more
 * type against the same rhythm, not a photocopy enlargement of a phone screen.
 */
import { FRAME } from "./scene.ts";

/** Double the app's 16px root. The film is the same design at a different distance. */
export const FILM_ROOT_PX = 32;

export function emitSceneCss(): string {
  return `/* Generated by packages/world. Do not edit by hand - edit scenes/css.ts. */

html {
  font-size: ${FILM_ROOT_PX}px;
}

/* A held frame. No animation and no transition anywhere in this file: the renderer takes
   one screenshot, and a moving page renders differently on a slower machine. */
.frame {
  box-sizing: border-box;
  width: ${FRAME.width}px;
  height: ${FRAME.height}px;
  display: grid;
  grid-template-rows: 1fr auto;
  overflow: hidden;
  background: var(--w-color-ground);
  color: var(--w-color-ink);
  padding: var(--w-space-9);
  gap: var(--w-space-6);
}

.stage {
  display: grid;
  min-height: 0;
  gap: var(--w-space-6);
}

.stage.centred {
  align-content: center;
  justify-items: center;
  text-align: center;
}

/* Words beside the photograph, never on top of it. Text over a family's own photograph is
   the single fastest way to make a memory look like an advertisement. */
.stage.split {
  grid-template-columns: 3fr 2fr;
  align-items: center;
  gap: var(--w-space-9);
  text-align: left;
}

.stage.wash {
  background: var(--w-color-saffron-wash);
  border-radius: var(--w-radius-sheet);
  padding: var(--w-space-9);
  align-content: center;
  justify-items: center;
  text-align: center;
}

.display {
  margin: 0;
  font-family: var(--w-font-display);
  font-weight: var(--w-weight-regular);
  line-height: var(--w-leading-tight);
  letter-spacing: var(--w-tracking-name);
  text-wrap: balance;
}

.name {
  font-size: var(--w-size-name);
}

.year {
  font-size: var(--w-size-year);
}

.chapter {
  font-size: var(--w-size-chapter);
}

.quiet {
  margin: 0;
  color: var(--w-color-ink-quiet);
  font-family: var(--w-font-body);
  line-height: var(--w-leading-read);
}

.lead {
  font-size: var(--w-size-lead);
}

.measure {
  max-width: var(--w-layout-measure);
}

.label {
  margin: 0;
  color: var(--w-color-ink-faint);
  font-family: var(--w-font-body);
  font-size: var(--w-size-fine);
  font-weight: var(--w-weight-medium);
  letter-spacing: var(--w-tracking-label);
  text-transform: uppercase;
}

.thread {
  width: var(--w-space-9);
  height: 0;
  margin: 0;
  border: 0;
  border-top: var(--w-space-hair) solid var(--w-color-thread);
}

.thread.short {
  width: var(--w-space-7);
}

/* "contain", not "cover". Cover crops, and what it crops out of a photograph of a small
   person is usually the top of their head. A letterboxed photograph on the ground colour
   is the whole picture; a cropped one is a decision nobody asked us to make. */
.picture {
  margin: 0;
  min-height: 0;
  height: 100%;
  display: grid;
  align-items: center;
}

.picture img {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: contain;
  border-radius: var(--w-radius-object);
}

.words {
  display: grid;
  gap: var(--w-space-5);
  align-content: center;
}

/* The caption band. It sits in its own grid row rather than over the picture, so a long
   transcript pushes the frame's layout instead of covering a photograph. */
.caption {
  display: grid;
  justify-items: center;
  border-top: var(--w-space-hair) solid var(--w-color-thread);
  padding-top: var(--w-space-5);
}

.caption p {
  margin: 0;
  max-width: var(--w-layout-measure);
  color: var(--w-color-ink);
  font-family: var(--w-font-body);
  font-size: var(--w-size-lead);
  line-height: var(--w-leading-read);
  text-align: center;
  text-wrap: pretty;
}
`;
}
