/**
 * Emits everything downstream consumers read:
 *
 *   dist/world.css   the custom properties, for the film scenes in Chromium
 *   dist/tokens.js   the same values as a plain module, for anything a browser loads
 *
 * The native app imports `src/` directly and needs neither. All three paths are fed by
 * the same source, which is the entire point of the package.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { emitCss } from "../src/css.ts";
import { COLORS, FONTS } from "../src/tokens.ts";
import { DURATION, EASING, ELEVATION, LAYOUT, LINE_HEIGHT, RADIUS, SPACE, TRACKING, TYPE_SIZE, WEIGHT } from "../src/scale.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

const css = emitCss();
writeFileSync(join(dist, "world.css"), css);

const js = `// Generated by packages/world. Do not edit by hand.
export const COLORS = ${JSON.stringify(COLORS, null, 2)};
export const FONTS = ${JSON.stringify(FONTS.map(({ name, stack, meaning }) => ({ name, stack, meaning })), null, 2)};
export const TYPE_SIZE = ${JSON.stringify(TYPE_SIZE)};
export const LINE_HEIGHT = ${JSON.stringify(LINE_HEIGHT)};
export const TRACKING = ${JSON.stringify(TRACKING)};
export const WEIGHT = ${JSON.stringify(WEIGHT)};
export const SPACE = ${JSON.stringify(SPACE)};
export const RADIUS = ${JSON.stringify(RADIUS)};
export const ELEVATION = ${JSON.stringify(ELEVATION)};
export const DURATION = ${JSON.stringify(DURATION)};
export const EASING = ${JSON.stringify(EASING)};
export const LAYOUT = ${JSON.stringify(LAYOUT)};
`;
writeFileSync(join(dist, "tokens.js"), js);

// The same values as data, so `tests/design` can hold the design language to the
// constitution from inside the Python gate without parsing TypeScript.
const json = {
  colors: COLORS,
  fonts: FONTS,
  typeSize: TYPE_SIZE,
  lineHeight: LINE_HEIGHT,
  tracking: TRACKING,
  weight: WEIGHT,
  space: SPACE,
  radius: RADIUS,
  elevation: ELEVATION,
  duration: DURATION,
  easing: EASING,
  layout: LAYOUT,
};
writeFileSync(join(dist, "tokens.json"), JSON.stringify(json, null, 2) + "\n");

console.log(`world.css  ${css.length} bytes\ntokens.js  ${js.length} bytes\ntokens.json emitted`);
