/**
 * Emits everything downstream consumers read:
 *
 *   dist/world.css   the custom properties, for the film scenes in Chromium
 *   dist/tokens.js   the same values as a plain module, for anything a browser loads
 *
 * The native app imports `src/` directly and needs neither. All three paths are fed by
 * the same source, which is the entire point of the package.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { emitCss } from "../src/css.ts";
import { emitSceneCss } from "../scenes/css.ts";
import { renderScene, SCENE_KINDS, type SceneInput } from "../scenes/scene.ts";
import { COLORS, FONTS } from "../src/tokens.ts";
import { DURATION, EASING, ELEVATION, LAYOUT, LINE_HEIGHT, RADIUS, SPACE, TRACKING, TYPE_SIZE, WEIGHT } from "../src/scale.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

const css = emitCss();
writeFileSync(join(dist, "world.css"), css);

// The film's layer, and one sample frame per kind. The samples exist so that "the film
// looks like the app" is something a person can open and look at, rather than a claim in a
// commit message. They are drawn from the same renderer the compiler's output goes through.
const sceneCss = emitSceneCss();
writeFileSync(join(dist, "scenes.css"), sceneCss);

const scenesDir = join(dist, "scenes");
mkdirSync(scenesDir, { recursive: true });
const SAMPLES: Record<string, SceneInput> = {
  OPENING: { id: "opening", kind: "OPENING", heading: "Aarav, 2026", body: "2026-03-04 - 2026-11-30" },
  SPARK: { id: "spark-1", kind: "SPARK", heading: "wanted to know why the moon follows the car" },
  MOMENT: {
    id: "moment-mom-1",
    kind: "MOMENT",
    heading: "first time down the slide alone",
    body: "He climbed back up before I could say anything.",
    // The samples are meant to be opened beside a real exported film, whose media folder
    // sits next to film.json. No stock photograph ships here to stand in for one.
    picture: "media/med-0001.jpg",
  },
  PROMISE_KEPT: {
    id: "promise-kept-1",
    kind: "PROMISE_KEPT",
    heading: "first time down the slide alone",
    body: "He climbed back up before I could say anything.",
    picture: "media/med-0001.jpg",
  },
  VOICE: {
    id: "moment-mom-2",
    kind: "VOICE",
    heading: "counting to twenty in the bath",
    body: "Six minutes, most of it wrong, none of it corrected.",
    narration: "you did it, you did it",
  },
  LITTLE_THING: { id: "little-1", kind: "LITTLE_THING", heading: "\u201cnot yet, Papa\u201d", body: "Said to a shoe." },
  CLOSING: {
    id: "closing",
    kind: "CLOSING",
    heading: "24 moments",
    body: "Everything here happened. Nothing here was invented.",
    narration: "[read by a machine] Everything here happened. Nothing here was invented.",
  },
};
for (const kind of SCENE_KINDS) {
  const scene = SAMPLES[kind]!;
  writeFileSync(
    join(scenesDir, `${kind.toLowerCase()}.html`),
    renderScene(scene, { worldCss: "../world.css", sceneCss: "../scenes.css" })
  );
}

const js = `// Generated by packages/world. Do not edit by hand.
export const COLORS = ${JSON.stringify(COLORS, null, 2)};
export const FONTS = ${JSON.stringify(FONTS.map(({ name, stack, meaning }) => ({ name, stack, meaning })), null, 2)};
export const TYPE_SIZE = ${JSON.stringify(TYPE_SIZE)};
export const LINE_HEIGHT = ${JSON.stringify(LINE_HEIGHT)};
export const TRACKING = ${JSON.stringify(TRACKING)};
export const WEIGHT = ${JSON.stringify(WEIGHT)};
export const SPACE = ${JSON.stringify(SPACE)};
export const RADIUS = ${JSON.stringify(RADIUS)};
export const ELEVATION = ${JSON.stringify(ELEVATION)};
export const DURATION = ${JSON.stringify(DURATION)};
export const EASING = ${JSON.stringify(EASING)};
export const LAYOUT = ${JSON.stringify(LAYOUT)};
`;
writeFileSync(join(dist, "tokens.js"), js);

// The same values as data, so `tests/design` can hold the design language to the
// constitution from inside the Python gate without parsing TypeScript.
const json = {
  colors: COLORS,
  fonts: FONTS,
  typeSize: TYPE_SIZE,
  lineHeight: LINE_HEIGHT,
  tracking: TRACKING,
  weight: WEIGHT,
  space: SPACE,
  radius: RADIUS,
  elevation: ELEVATION,
  duration: DURATION,
  easing: EASING,
  layout: LAYOUT,
};
writeFileSync(join(dist, "tokens.json"), JSON.stringify(json, null, 2) + "\n");

console.log(
  `world.css  ${css.length} bytes\nscenes.css ${sceneCss.length} bytes\n` +
    `tokens.js  ${js.length} bytes\ntokens.json emitted\n` +
    `scenes     ${SCENE_KINDS.length} sample frames`
);
