/**
 * Print-specific CSS Paged Media rules.
 *
 * Provides print typography, margins, bleed, page breaks, and spread layouts
 * using @anuvritti/world design tokens.
 */
export function emitPrintCss(): string {
  return `/* Print-specific layout rules. Generated by @anuvritti/world/print. */
@page {
  size: A4 portrait;
  margin: 20mm 15mm 25mm 15mm;
  @bottom-right {
    content: counter(page);
    font-family: var(--w-font-mono);
    font-size: var(--w-size-micro);
    color: var(--w-color-ink-faint);
  }
}

@page :first {
  @bottom-right {
    content: none;
  }
}

@media print {
  body {
    background: #FFFFFF !important;
    color: var(--w-color-ink) !important;
    font-size: 11pt;
    line-height: 1.5;
  }

  .print-page {
    page-break-after: always;
    break-after: page;
    min-height: 100%;
    display: flex;
    flex-direction: column;
    justify-content: center;
  }

  .page-cover {
    page-break-after: always;
    break-after: page;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    text-align: center;
    min-height: 80vh;
  }

  .page-spread {
    page-break-inside: avoid;
    break-inside: avoid;
    margin-bottom: 2rem;
  }

  .print-photo {
    max-width: 100%;
    max-height: 120mm;
    object-fit: contain;
    border-radius: var(--w-radius-cut);
    border: 1px solid var(--w-color-thread);
    margin: 1rem 0;
  }

  .print-citation-list {
    margin-top: 1rem;
    padding-top: 0.5rem;
    border-top: 1px solid var(--w-color-thread);
    font-family: var(--w-font-mono);
    font-size: var(--w-size-micro);
    color: var(--w-color-ink-faint);
  }

  .colophon {
    page-break-before: always;
    break-before: page;
    margin-top: auto;
    font-size: var(--w-size-fine);
    color: var(--w-color-ink-quiet);
    border-top: 1px solid var(--w-color-thread);
    padding-top: 1rem;
  }
}
`;
}
